#server
server:
  port: 9527


#spring
spring:
  application:
    name: simpler-mybatis

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpler?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  # thymeleaf start
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/