#server
server:
  port: 8080


#spring
spring:
  application:
    name: simpler-mybatis

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rpt?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # thymeleaf start
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/


# Redis数据库索引（默认为0）
  redis:
    database: 0
# Redis服务器地址
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password:
    jedis:
        pool:
           max-active: 8
           max-idle: 8
           min-idle: 0
           max-wait: -1ms
    timeout: 6000ms
filePath: E:/var
